### ISSUE TITLE
missing BuildRequires: flex-devel

### ISSUE THREAD

**Issue by NuxRo** [nkadel/vtwm-5.5.x-srpm#1]
Hi, you need flex-devel to build this (on EL7).
I have added it to my nux-dextop repo btw.

**Comment by nkadel** [comment]
flex-devel does not exist for RHEL 5, the include file is therefor safer to include specifically.

I've updated it with other RHEL 7 dependencies, including some X11 include files to avod having to sort out package naming practices for RHEL 5, 6, and 7. I've also explicitly added "flex", which flex-devel did not include, and libpng and libpng-devel.

Try and enjoy!
